// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as interfaces$0 from "../interfaces/models.js";

export class ProfileSummary {
    "id": string;
    "name": string;
    "source": string;
    "updatedAt"?: string;
    "nodeCount": number;
    "remainingBytes"?: number;
    "expiresAt"?: string;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

export class ProfileTaskRequest {
    "profileId": string;
    "name"?: string;
    "preset": string;
    "presets"?: string[];
    "config"?: interfaces$0.TaskConfig;

    /** Creates a new ProfileTaskRequest instance. */
    constructor($$source: Partial<ProfileTaskRequest> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileTaskRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileTaskRequest {
        const $$createField3_0 = $$createType0;
        const $$createField4_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField3_0($$parsedSource["presets"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        return new ProfileTaskRequest($$parsedSource as Partial<ProfileTaskRequest>);
    }
}

export class ReleaseCheckResult {
    "currentVersion": string;
    "latestVersion"?: string;
    "releaseName"?: string;
    "releaseURL"?: string;
    "releaseNotes"?: string;
    "hasUpdate": boolean;
    "checkedAt"?: string;

    /** Creates a new ReleaseCheckResult instance. */
    constructor($$source: Partial<ReleaseCheckResult> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseCheckResult($$parsedSource as Partial<ReleaseCheckResult>);
    }
}

export class RemoteProfileTaskRequest {
    "profileId": string;
    "knightIds": string[];
    "name"?: string;
    "preset": string;
    "presets"?: string[];
    "config"?: interfaces$0.TaskConfig;

    /** Creates a new RemoteProfileTaskRequest instance. */
    constructor($$source: Partial<RemoteProfileTaskRequest> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("knightIds" in $$source)) {
            this["knightIds"] = [];
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteProfileTaskRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteProfileTaskRequest {
        const $$createField1_0 = $$createType0;
        const $$createField4_0 = $$createType0;
        const $$createField5_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("knightIds" in $$parsedSource) {
            $$parsedSource["knightIds"] = $$createField1_0($$parsedSource["knightIds"]);
        }
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField4_0($$parsedSource["presets"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField5_0($$parsedSource["config"]);
        }
        return new RemoteProfileTaskRequest($$parsedSource as Partial<RemoteProfileTaskRequest>);
    }
}

export class Settings {
    "language": string;
    "dns": interfaces$0.DNSConfig;
    "hideProfileNameInExport": boolean;
    "hideCNInboundInExport": boolean;

    /** Creates a new Settings instance. */
    constructor($$source: Partial<Settings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("dns" in $$source)) {
            this["dns"] = (new interfaces$0.DNSConfig());
        }
        if (!("hideProfileNameInExport" in $$source)) {
            this["hideProfileNameInExport"] = false;
        }
        if (!("hideCNInboundInExport" in $$source)) {
            this["hideCNInboundInExport"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Settings instance from a string or object.
     */
    static createFrom($$source: any = {}): Settings {
        const $$createField1_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        return new Settings($$parsedSource as Partial<Settings>);
    }
}

export class SettingsPatch {
    "language"?: string;
    "dns"?: interfaces$0.DNSConfig | null;
    "hideProfileNameInExport"?: boolean | null;
    "hideCNInboundInExport"?: boolean | null;

    /** Creates a new SettingsPatch instance. */
    constructor($$source: Partial<SettingsPatch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SettingsPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): SettingsPatch {
        const $$createField1_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        return new SettingsPatch($$parsedSource as Partial<SettingsPatch>);
    }
}

export class Status {
    "profilesPath": string;
    "settingsPath"?: string;
    "runtime": interfaces$0.RuntimeStatus;
    "mihomoVersion"?: string;
    "networkEnv": interfaces$0.BackendInfo;
    "remote"?: interfaces$0.ClusterStatus;
    "lastNetworkProbe"?: string;
    "networkProbeBusy"?: boolean;

    /** Creates a new Status instance. */
    constructor($$source: Partial<Status> = {}) {
        if (!("profilesPath" in $$source)) {
            this["profilesPath"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new interfaces$0.RuntimeStatus());
        }
        if (!("networkEnv" in $$source)) {
            this["networkEnv"] = (new interfaces$0.BackendInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Status instance from a string or object.
     */
    static createFrom($$source: any = {}): Status {
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        const $$createField5_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField2_0($$parsedSource["runtime"]);
        }
        if ("networkEnv" in $$parsedSource) {
            $$parsedSource["networkEnv"] = $$createField4_0($$parsedSource["networkEnv"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField5_0($$parsedSource["remote"]);
        }
        return new Status($$parsedSource as Partial<Status>);
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = interfaces$0.TaskConfig.createFrom;
const $$createType2 = interfaces$0.DNSConfig.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = interfaces$0.RuntimeStatus.createFrom;
const $$createType5 = interfaces$0.BackendInfo.createFrom;
const $$createType6 = interfaces$0.ClusterStatus.createFrom;
