// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

export class BackendInfo {
    "ip"?: string;
    "location"?: string;
    "source"?: string;
    "updatedAt"?: string;
    "error"?: string;

    /** Creates a new BackendInfo instance. */
    constructor($$source: Partial<BackendInfo> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BackendInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): BackendInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BackendInfo($$parsedSource as Partial<BackendInfo>);
    }
}

export class ClusterConnectedKnight {
    "knightId": string;
    "knightName"?: string;
    "state": ClusterKnightState;
    "remoteAddr"?: string;
    "lastSeenAt"?: string;
    "lastError"?: string;

    /** Creates a new ClusterConnectedKnight instance. */
    constructor($$source: Partial<ClusterConnectedKnight> = {}) {
        if (!("knightId" in $$source)) {
            this["knightId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = ClusterKnightState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterConnectedKnight instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterConnectedKnight {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterConnectedKnight($$parsedSource as Partial<ClusterConnectedKnight>);
    }
}

export enum ClusterKnightState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterKnightStatePaired = "paired",
    ClusterKnightStateOnline = "online",
    ClusterKnightStateBusy = "busy",
    ClusterKnightStateOffline = "offline",
    ClusterKnightStateRevoked = "revoked",
};

export class ClusterKnightStatus {
    "bound": boolean;
    "knightId"?: string;
    "knightName"?: string;
    "masterHost"?: string;
    "masterPort"?: number;
    "connected": boolean;
    "lastSeenAt"?: string;
    "lastError"?: string;

    /** Creates a new ClusterKnightStatus instance. */
    constructor($$source: Partial<ClusterKnightStatus> = {}) {
        if (!("bound" in $$source)) {
            this["bound"] = false;
        }
        if (!("connected" in $$source)) {
            this["connected"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterKnightStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterKnightStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterKnightStatus($$parsedSource as Partial<ClusterKnightStatus>);
    }
}

export class ClusterMasterStatus {
    "enabled": boolean;
    "listenHost"?: string;
    "listenPort"?: number;
    "eligibility": MasterEligibility;

    /** Creates a new ClusterMasterStatus instance. */
    constructor($$source: Partial<ClusterMasterStatus> = {}) {
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }
        if (!("eligibility" in $$source)) {
            this["eligibility"] = (new MasterEligibility());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterMasterStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterMasterStatus {
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("eligibility" in $$parsedSource) {
            $$parsedSource["eligibility"] = $$createField3_0($$parsedSource["eligibility"]);
        }
        return new ClusterMasterStatus($$parsedSource as Partial<ClusterMasterStatus>);
    }
}

export class ClusterPairingCode {
    "code": string;
    "knightName"?: string;
    "expiresAt"?: string;

    /** Creates a new ClusterPairingCode instance. */
    constructor($$source: Partial<ClusterPairingCode> = {}) {
        if (!("code" in $$source)) {
            this["code"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterPairingCode instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterPairingCode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ClusterPairingCode($$parsedSource as Partial<ClusterPairingCode>);
    }
}

export class ClusterRemoteTask {
    "assignmentId": string;
    "remoteTaskId": string;
    "knightId": string;
    "knightName"?: string;
    "taskName"?: string;
    "state": ClusterRemoteTaskState;
    "createdAt"?: string;
    "startedAt"?: string;
    "finishedAt"?: string;
    "exitCode"?: string;
    "error"?: string;
    "archiveTaskId"?: string;
    "localTaskId"?: string;
    "runtime"?: TaskState | null;

    /** Creates a new ClusterRemoteTask instance. */
    constructor($$source: Partial<ClusterRemoteTask> = {}) {
        if (!("assignmentId" in $$source)) {
            this["assignmentId"] = "";
        }
        if (!("remoteTaskId" in $$source)) {
            this["remoteTaskId"] = "";
        }
        if (!("knightId" in $$source)) {
            this["knightId"] = "";
        }
        if (!("state" in $$source)) {
            this["state"] = ClusterRemoteTaskState.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterRemoteTask instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterRemoteTask {
        const $$createField13_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField13_0($$parsedSource["runtime"]);
        }
        return new ClusterRemoteTask($$parsedSource as Partial<ClusterRemoteTask>);
    }
}

export enum ClusterRemoteTaskState {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterRemoteTaskQueued = "queued",
    ClusterRemoteTaskRunning = "running",
    ClusterRemoteTaskFinished = "finished",
    ClusterRemoteTaskFailed = "failed",
};

export enum ClusterRole {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ClusterRoleStandalone = "standalone",
    ClusterRoleMaster = "master",
    ClusterRoleKnight = "knight",
};

export class ClusterStatus {
    "role": ClusterRole;
    "master"?: ClusterMasterStatus | null;
    "knight"?: ClusterKnightStatus | null;

    /** Creates a new ClusterStatus instance. */
    constructor($$source: Partial<ClusterStatus> = {}) {
        if (!("role" in $$source)) {
            this["role"] = ClusterRole.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ClusterStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): ClusterStatus {
        const $$createField1_0 = $$createType4;
        const $$createField2_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("master" in $$parsedSource) {
            $$parsedSource["master"] = $$createField1_0($$parsedSource["master"]);
        }
        if ("knight" in $$parsedSource) {
            $$parsedSource["knight"] = $$createField2_0($$parsedSource["knight"]);
        }
        return new ClusterStatus($$parsedSource as Partial<ClusterStatus>);
    }
}

export class DNSConfig {
    "bootstrapServers": string[];
    "resolverServers": string[];

    /** Creates a new DNSConfig instance. */
    constructor($$source: Partial<DNSConfig> = {}) {
        if (!("bootstrapServers" in $$source)) {
            this["bootstrapServers"] = [];
        }
        if (!("resolverServers" in $$source)) {
            this["resolverServers"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DNSConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): DNSConfig {
        const $$createField0_0 = $$createType7;
        const $$createField1_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("bootstrapServers" in $$parsedSource) {
            $$parsedSource["bootstrapServers"] = $$createField0_0($$parsedSource["bootstrapServers"]);
        }
        if ("resolverServers" in $$parsedSource) {
            $$parsedSource["resolverServers"] = $$createField1_0($$parsedSource["resolverServers"]);
        }
        return new DNSConfig($$parsedSource as Partial<DNSConfig>);
    }
}

export class DownloadTarget {
    "id": string;
    "source": DownloadTargetSource;
    "name": string;
    "city"?: string;
    "country"?: string;
    "countryCode"?: string;
    "sponsor"?: string;
    "host"?: string;
    "endpoint"?: string;
    "downloadURL": string;

    /** Creates a new DownloadTarget instance. */
    constructor($$source: Partial<DownloadTarget> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = DownloadTargetSource.$zero;
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DownloadTarget instance from a string or object.
     */
    static createFrom($$source: any = {}): DownloadTarget {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new DownloadTarget($$parsedSource as Partial<DownloadTarget>);
    }
}

export enum DownloadTargetSource {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    DownloadTargetSourceCloudflare = "cloudflare",
    DownloadTargetSourceSpeedtest = "speedtest",
};

export class EntryResult {
    "proxyInfo": ProxyInfo;
    "invokeDuration": number;
    "matrices": MatrixResult[];
    "error"?: string;

    /** Creates a new EntryResult instance. */
    constructor($$source: Partial<EntryResult> = {}) {
        if (!("proxyInfo" in $$source)) {
            this["proxyInfo"] = (new ProxyInfo());
        }
        if (!("invokeDuration" in $$source)) {
            this["invokeDuration"] = 0;
        }
        if (!("matrices" in $$source)) {
            this["matrices"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new EntryResult instance from a string or object.
     */
    static createFrom($$source: any = {}): EntryResult {
        const $$createField0_0 = $$createType8;
        const $$createField2_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("proxyInfo" in $$parsedSource) {
            $$parsedSource["proxyInfo"] = $$createField0_0($$parsedSource["proxyInfo"]);
        }
        if ("matrices" in $$parsedSource) {
            $$parsedSource["matrices"] = $$createField2_0($$parsedSource["matrices"]);
        }
        return new EntryResult($$parsedSource as Partial<EntryResult>);
    }
}

export enum MacroType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MacroPing = "PING",
    MacroUDP = "UDP",
    MacroSpeed = "SPEED",
    MacroGeo = "GEO",
    MacroMedia = "MEDIA",
    MacroInvalid = "INVALID",
};

export class MasterEligibility {
    "publicIP"?: string;
    "hasPublicIP": boolean;
    "natType"?: string;
    "isNat1": boolean;
    "reachable": boolean;
    "eligible": boolean;
    "checkedAt"?: string;
    "error"?: string;

    /** Creates a new MasterEligibility instance. */
    constructor($$source: Partial<MasterEligibility> = {}) {
        if (!("hasPublicIP" in $$source)) {
            this["hasPublicIP"] = false;
        }
        if (!("isNat1" in $$source)) {
            this["isNat1"] = false;
        }
        if (!("reachable" in $$source)) {
            this["reachable"] = false;
        }
        if (!("eligible" in $$source)) {
            this["eligible"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MasterEligibility instance from a string or object.
     */
    static createFrom($$source: any = {}): MasterEligibility {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MasterEligibility($$parsedSource as Partial<MasterEligibility>);
    }
}

export class MatrixEntry {
    "type": MatrixType;
    "params"?: string;

    /** Creates a new MatrixEntry instance. */
    constructor($$source: Partial<MatrixEntry> = {}) {
        if (!("type" in $$source)) {
            this["type"] = MatrixType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatrixEntry instance from a string or object.
     */
    static createFrom($$source: any = {}): MatrixEntry {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatrixEntry($$parsedSource as Partial<MatrixEntry>);
    }
}

export class MatrixResult {
    "type": MatrixType;
    "payload": any;

    /** Creates a new MatrixResult instance. */
    constructor($$source: Partial<MatrixResult> = {}) {
        if (!("type" in $$source)) {
            this["type"] = MatrixType.$zero;
        }
        if (!("payload" in $$source)) {
            this["payload"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MatrixResult instance from a string or object.
     */
    static createFrom($$source: any = {}): MatrixResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MatrixResult($$parsedSource as Partial<MatrixResult>);
    }
}

export enum MatrixType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    MatrixHTTPPing = "TEST_PING_CONN",
    MatrixRTTPing = "TEST_PING_RTT",
    MatrixUDPNATType = "UDP_NAT_TYPE",
    MatrixAverageSpeed = "SPEED_AVERAGE",
    MatrixMaxSpeed = "SPEED_MAX",
    MatrixPerSecSpeed = "SPEED_PER_SECOND",
    MatrixTrafficUsed = "SPEED_TRAFFIC_USED",
    MatrixInboundGeoIP = "GEOIP_INBOUND",
    MatrixOutboundGeoIP = "GEOIP_OUTBOUND",
    MatrixMediaUnlock = "MEDIA_UNLOCK",
    MatrixInvalid = "INVALID",
};

export class Node {
    "name": string;
    "order"?: number;
    "protocol"?: string;
    "server"?: string;
    "port"?: string;
    "udp"?: boolean | null;
    "payload"?: string;
    "enabled": boolean;

    /** Creates a new Node instance. */
    constructor($$source: Partial<Node> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("enabled" in $$source)) {
            this["enabled"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Node instance from a string or object.
     */
    static createFrom($$source: any = {}): Node {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new Node($$parsedSource as Partial<Node>);
    }
}

export class Profile {
    "id": string;
    "name": string;
    "source": string;
    "nodes": Node[];
    "updatedAt"?: string;
    "attributes"?: any;

    /** Creates a new Profile instance. */
    constructor($$source: Partial<Profile> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Profile instance from a string or object.
     */
    static createFrom($$source: any = {}): Profile {
        const $$createField3_0 = $$createType12;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField3_0($$parsedSource["nodes"]);
        }
        return new Profile($$parsedSource as Partial<Profile>);
    }
}

export class ProfileImportRequest {
    "name": string;
    "source": string;
    "attributes"?: any;

    /** Creates a new ProfileImportRequest instance. */
    constructor($$source: Partial<ProfileImportRequest> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileImportRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileImportRequest {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileImportRequest($$parsedSource as Partial<ProfileImportRequest>);
    }
}

export class ProxyInfo {
    "name": string;
    "address": string;
    "type": ProxyType;

    /** Creates a new ProxyInfo instance. */
    constructor($$source: Partial<ProxyInfo> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("address" in $$source)) {
            this["address"] = "";
        }
        if (!("type" in $$source)) {
            this["type"] = ProxyType.$zero;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProxyInfo instance from a string or object.
     */
    static createFrom($$source: any = {}): ProxyInfo {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProxyInfo($$parsedSource as Partial<ProxyInfo>);
    }
}

export enum ProxyType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    ProxyUnknown = "unknown",
    ProxyShadowsocks = "shadowsocks",
    ProxySSR = "ssr",
    ProxySocks5 = "socks5",
    ProxyHTTP = "http",
    ProxyVMess = "vmess",
    ProxyTrojan = "trojan",
    ProxyVLESS = "vless",
    ProxyHysteria = "hysteria",
    ProxyHysteria2 = "hysteria2",
    ProxyTuic = "tuic",
    ProxyAnyTLS = "anytls",
};

export class RemoteExecutionContext {
    "mode"?: RemoteExecutionMode;
    "remoteTaskId"?: string;
    "masterId"?: string;
    "masterName"?: string;
    "knightId"?: string;
    "knightName"?: string;
    "assignmentId"?: string;

    /** Creates a new RemoteExecutionContext instance. */
    constructor($$source: Partial<RemoteExecutionContext> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RemoteExecutionContext instance from a string or object.
     */
    static createFrom($$source: any = {}): RemoteExecutionContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RemoteExecutionContext($$parsedSource as Partial<RemoteExecutionContext>);
    }
}

export enum RemoteExecutionMode {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    RemoteExecutionModeLocal = "local",
    RemoteExecutionModeRemoteMaster = "remote-master",
    RemoteExecutionModeRemoteKnight = "remote-knight",
};

export class ResultArchive {
    "version": number;
    "task": ResultArchiveTask;
    "state": TaskState;
    "results"?: EntryResult[];
    "exitCode"?: string;
    "report": ResultReport;

    /** Creates a new ResultArchive instance. */
    constructor($$source: Partial<ResultArchive> = {}) {
        if (!("version" in $$source)) {
            this["version"] = 0;
        }
        if (!("task" in $$source)) {
            this["task"] = (new ResultArchiveTask());
        }
        if (!("state" in $$source)) {
            this["state"] = (new TaskState());
        }
        if (!("report" in $$source)) {
            this["report"] = (new ResultReport());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultArchive instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultArchive {
        const $$createField1_0 = $$createType13;
        const $$createField2_0 = $$createType1;
        const $$createField3_0 = $$createType15;
        const $$createField5_0 = $$createType16;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField1_0($$parsedSource["task"]);
        }
        if ("state" in $$parsedSource) {
            $$parsedSource["state"] = $$createField2_0($$parsedSource["state"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField3_0($$parsedSource["results"]);
        }
        if ("report" in $$parsedSource) {
            $$parsedSource["report"] = $$createField5_0($$parsedSource["report"]);
        }
        return new ResultArchive($$parsedSource as Partial<ResultArchive>);
    }
}

export class ResultArchiveListItem {
    "taskId": string;
    "taskName": string;
    "preset"?: string;
    "profileId"?: string;
    "profileName"?: string;
    "knightName"?: string;
    "startedAt"?: string;
    "finishedAt"?: string;
    "exitCode"?: string;
    "nodeCount": number;
    "sectionCount": number;

    /** Creates a new ResultArchiveListItem instance. */
    constructor($$source: Partial<ResultArchiveListItem> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("taskName" in $$source)) {
            this["taskName"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }
        if (!("sectionCount" in $$source)) {
            this["sectionCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultArchiveListItem instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultArchiveListItem {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultArchiveListItem($$parsedSource as Partial<ResultArchiveListItem>);
    }
}

export class ResultArchiveNode {
    "name": string;
    "order"?: number;

    /** Creates a new ResultArchiveNode instance. */
    constructor($$source: Partial<ResultArchiveNode> = {}) {
        if (!("name" in $$source)) {
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultArchiveNode instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultArchiveNode {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultArchiveNode($$parsedSource as Partial<ResultArchiveNode>);
    }
}

export class ResultArchiveTask {
    "id": string;
    "name": string;
    "vendor": VendorType;
    "context"?: TaskContext;
    "environment"?: TaskEnvironment | null;
    "nodes": ResultArchiveNode[];
    "matrices": MatrixEntry[];
    "config": TaskConfig;

    /** Creates a new ResultArchiveTask instance. */
    constructor($$source: Partial<ResultArchiveTask> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("vendor" in $$source)) {
            this["vendor"] = VendorType.$zero;
        }
        if (!("nodes" in $$source)) {
            this["nodes"] = [];
        }
        if (!("matrices" in $$source)) {
            this["matrices"] = [];
        }
        if (!("config" in $$source)) {
            this["config"] = (new TaskConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultArchiveTask instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultArchiveTask {
        const $$createField3_0 = $$createType17;
        const $$createField4_0 = $$createType19;
        const $$createField5_0 = $$createType21;
        const $$createField6_0 = $$createType23;
        const $$createField7_0 = $$createType24;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("context" in $$parsedSource) {
            $$parsedSource["context"] = $$createField3_0($$parsedSource["context"]);
        }
        if ("environment" in $$parsedSource) {
            $$parsedSource["environment"] = $$createField4_0($$parsedSource["environment"]);
        }
        if ("nodes" in $$parsedSource) {
            $$parsedSource["nodes"] = $$createField5_0($$parsedSource["nodes"]);
        }
        if ("matrices" in $$parsedSource) {
            $$parsedSource["matrices"] = $$createField6_0($$parsedSource["matrices"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField7_0($$parsedSource["config"]);
        }
        return new ResultArchiveTask($$parsedSource as Partial<ResultArchiveTask>);
    }
}

export class ResultReport {
    "generatedAt": string;
    "sections"?: ResultReportSection[];

    /** Creates a new ResultReport instance. */
    constructor($$source: Partial<ResultReport> = {}) {
        if (!("generatedAt" in $$source)) {
            this["generatedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultReport instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultReport {
        const $$createField1_0 = $$createType26;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("sections" in $$parsedSource) {
            $$parsedSource["sections"] = $$createField1_0($$parsedSource["sections"]);
        }
        return new ResultReport($$parsedSource as Partial<ResultReport>);
    }
}

export class ResultReportColumn {
    "key": string;
    "label": string;

    /** Creates a new ResultReportColumn instance. */
    constructor($$source: Partial<ResultReportColumn> = {}) {
        if (!("key" in $$source)) {
            this["key"] = "";
        }
        if (!("label" in $$source)) {
            this["label"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultReportColumn instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultReportColumn {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ResultReportColumn($$parsedSource as Partial<ResultReportColumn>);
    }
}

export class ResultReportSection {
    "kind": string;
    "title": string;
    "columns"?: ResultReportColumn[];
    "rows"?: { [_ in string]?: any }[];
    "summary"?: { [_ in string]?: any };

    /** Creates a new ResultReportSection instance. */
    constructor($$source: Partial<ResultReportSection> = {}) {
        if (!("kind" in $$source)) {
            this["kind"] = "";
        }
        if (!("title" in $$source)) {
            this["title"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ResultReportSection instance from a string or object.
     */
    static createFrom($$source: any = {}): ResultReportSection {
        const $$createField2_0 = $$createType28;
        const $$createField3_0 = $$createType30;
        const $$createField4_0 = $$createType29;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField2_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField3_0($$parsedSource["rows"]);
        }
        if ("summary" in $$parsedSource) {
            $$parsedSource["summary"] = $$createField4_0($$parsedSource["summary"]);
        }
        return new ResultReportSection($$parsedSource as Partial<ResultReportSection>);
    }
}

export class RuntimeStatus {
    "running": boolean;
    "runningTask": number;
    "totalTask": number;

    /** Creates a new RuntimeStatus instance. */
    constructor($$source: Partial<RuntimeStatus> = {}) {
        if (!("running" in $$source)) {
            this["running"] = false;
        }
        if (!("runningTask" in $$source)) {
            this["runningTask"] = 0;
        }
        if (!("totalTask" in $$source)) {
            this["totalTask"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RuntimeStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): RuntimeStatus {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RuntimeStatus($$parsedSource as Partial<RuntimeStatus>);
    }
}

export class TaskActiveNode {
    "nodeIndex": number;
    "nodeName": string;
    "nodeAddress"?: string;
    "protocol"?: ProxyType;
    "attempt"?: number;
    "phase"?: TaskRuntimePhase;
    "macro"?: MacroType;
    "matrix"?: MatrixType;
    "matrices"?: MatrixType[];
    "updatedAt"?: string;

    /** Creates a new TaskActiveNode instance. */
    constructor($$source: Partial<TaskActiveNode> = {}) {
        if (!("nodeIndex" in $$source)) {
            this["nodeIndex"] = 0;
        }
        if (!("nodeName" in $$source)) {
            this["nodeName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskActiveNode instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskActiveNode {
        const $$createField8_0 = $$createType31;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("matrices" in $$parsedSource) {
            $$parsedSource["matrices"] = $$createField8_0($$parsedSource["matrices"]);
        }
        return new TaskActiveNode($$parsedSource as Partial<TaskActiveNode>);
    }
}

export class TaskConfig {
    "pingAddress": string;
    "pingAverageOver": number;
    "taskRetry": number;
    "taskTimeoutMillis": number;
    "downloadURL": string;
    "downloadDuration": number;
    "downloadThreading": number;
    "backendIdentity"?: string;

    /** Creates a new TaskConfig instance. */
    constructor($$source: Partial<TaskConfig> = {}) {
        if (!("pingAddress" in $$source)) {
            this["pingAddress"] = "";
        }
        if (!("pingAverageOver" in $$source)) {
            this["pingAverageOver"] = 0;
        }
        if (!("taskRetry" in $$source)) {
            this["taskRetry"] = 0;
        }
        if (!("taskTimeoutMillis" in $$source)) {
            this["taskTimeoutMillis"] = 0;
        }
        if (!("downloadURL" in $$source)) {
            this["downloadURL"] = "";
        }
        if (!("downloadDuration" in $$source)) {
            this["downloadDuration"] = 0;
        }
        if (!("downloadThreading" in $$source)) {
            this["downloadThreading"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskConfig instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskConfig {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskConfig($$parsedSource as Partial<TaskConfig>);
    }
}

export class TaskContext {
    "preset"?: string;
    "profileId"?: string;
    "profileName"?: string;
    "profileSource"?: string;

    /** Creates a new TaskContext instance. */
    constructor($$source: Partial<TaskContext> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskContext instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskContext {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TaskContext($$parsedSource as Partial<TaskContext>);
    }
}

export class TaskEnvironment {
    "identity"?: string;
    "backend"?: BackendInfo | null;
    "remote"?: RemoteExecutionContext | null;

    /** Creates a new TaskEnvironment instance. */
    constructor($$source: Partial<TaskEnvironment> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskEnvironment instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskEnvironment {
        const $$createField1_0 = $$createType33;
        const $$createField2_0 = $$createType35;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("backend" in $$parsedSource) {
            $$parsedSource["backend"] = $$createField1_0($$parsedSource["backend"]);
        }
        if ("remote" in $$parsedSource) {
            $$parsedSource["remote"] = $$createField2_0($$parsedSource["remote"]);
        }
        return new TaskEnvironment($$parsedSource as Partial<TaskEnvironment>);
    }
}

export enum TaskRuntimePhase {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    TaskRuntimePhasePreparing = "preparing",
    TaskRuntimePhaseMacro = "macro",
    TaskRuntimePhaseMatrix = "matrix",
};

export class TaskState {
    "taskId": string;
    "name": string;
    "status": string;
    "progress": number;
    "total": number;
    "queuing": number;
    "startedAt": string;
    "finishedAt"?: string;
    "activeNodes"?: TaskActiveNode[];

    /** Creates a new TaskState instance. */
    constructor($$source: Partial<TaskState> = {}) {
        if (!("taskId" in $$source)) {
            this["taskId"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("status" in $$source)) {
            this["status"] = "";
        }
        if (!("progress" in $$source)) {
            this["progress"] = 0;
        }
        if (!("total" in $$source)) {
            this["total"] = 0;
        }
        if (!("queuing" in $$source)) {
            this["queuing"] = 0;
        }
        if (!("startedAt" in $$source)) {
            this["startedAt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskState instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskState {
        const $$createField8_0 = $$createType37;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("activeNodes" in $$parsedSource) {
            $$parsedSource["activeNodes"] = $$createField8_0($$parsedSource["activeNodes"]);
        }
        return new TaskState($$parsedSource as Partial<TaskState>);
    }
}

export class TaskStatusResponse {
    "task": TaskState;
    "results"?: EntryResult[];
    "exitCode"?: string;

    /** Creates a new TaskStatusResponse instance. */
    constructor($$source: Partial<TaskStatusResponse> = {}) {
        if (!("task" in $$source)) {
            this["task"] = (new TaskState());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TaskStatusResponse instance from a string or object.
     */
    static createFrom($$source: any = {}): TaskStatusResponse {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType15;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("task" in $$parsedSource) {
            $$parsedSource["task"] = $$createField0_0($$parsedSource["task"]);
        }
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField1_0($$parsedSource["results"]);
        }
        return new TaskStatusResponse($$parsedSource as Partial<TaskStatusResponse>);
    }
}

export enum VendorType {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero = "",

    VendorMihomo = "mihomo",
    VendorLocal = "local",
    VendorInvalid = "invalid",
};

// Private type creation functions
const $$createType0 = MasterEligibility.createFrom;
const $$createType1 = TaskState.createFrom;
const $$createType2 = $Create.Nullable($$createType1);
const $$createType3 = ClusterMasterStatus.createFrom;
const $$createType4 = $Create.Nullable($$createType3);
const $$createType5 = ClusterKnightStatus.createFrom;
const $$createType6 = $Create.Nullable($$createType5);
const $$createType7 = $Create.Array($Create.Any);
const $$createType8 = ProxyInfo.createFrom;
const $$createType9 = MatrixResult.createFrom;
const $$createType10 = $Create.Array($$createType9);
const $$createType11 = Node.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = ResultArchiveTask.createFrom;
const $$createType14 = EntryResult.createFrom;
const $$createType15 = $Create.Array($$createType14);
const $$createType16 = ResultReport.createFrom;
const $$createType17 = TaskContext.createFrom;
const $$createType18 = TaskEnvironment.createFrom;
const $$createType19 = $Create.Nullable($$createType18);
const $$createType20 = ResultArchiveNode.createFrom;
const $$createType21 = $Create.Array($$createType20);
const $$createType22 = MatrixEntry.createFrom;
const $$createType23 = $Create.Array($$createType22);
const $$createType24 = TaskConfig.createFrom;
const $$createType25 = ResultReportSection.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = ResultReportColumn.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Map($Create.Any, $Create.Any);
const $$createType30 = $Create.Array($$createType29);
const $$createType31 = $Create.Array($Create.Any);
const $$createType32 = BackendInfo.createFrom;
const $$createType33 = $Create.Nullable($$createType32);
const $$createType34 = RemoteExecutionContext.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = TaskActiveNode.createFrom;
const $$createType37 = $Create.Array($$createType36);
