// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as app$0 from "../sakiko.local/sakiko-core/app/models.js";

export const AppSettings = app$0.Settings;
export type AppSettings = app$0.Settings;

export const AppSettingsPatch = app$0.SettingsPatch;
export type AppSettingsPatch = app$0.SettingsPatch;

export const DesktopStatus = app$0.Status;
export type DesktopStatus = app$0.Status;

export const ProfileSummary = app$0.ProfileSummary;
export type ProfileSummary = app$0.ProfileSummary;

export const ProfileTaskSubmitRequest = app$0.ProfileTaskRequest;
export type ProfileTaskSubmitRequest = app$0.ProfileTaskRequest;

export const ReleaseCheckResult = app$0.ReleaseCheckResult;
export type ReleaseCheckResult = app$0.ReleaseCheckResult;

export const RemoteProfileTaskSubmitRequest = app$0.RemoteProfileTaskRequest;
export type RemoteProfileTaskSubmitRequest = app$0.RemoteProfileTaskRequest;
