// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as interfaces$0 from "../sakiko.local/sakiko-core/interfaces/models.js";

export class DesktopStatus {
    "profilesPath": string;
    "runtime": interfaces$0.RuntimeStatus;

    /** Creates a new DesktopStatus instance. */
    constructor($$source: Partial<DesktopStatus> = {}) {
        if (!("profilesPath" in $$source)) {
            this["profilesPath"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new interfaces$0.RuntimeStatus());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopStatus {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField1_0($$parsedSource["runtime"]);
        }
        return new DesktopStatus($$parsedSource as Partial<DesktopStatus>);
    }
}

export class ProfileSummary {
    "id": string;
    "name": string;
    "source": string;
    "updatedAt"?: string;
    "nodeCount": number;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

export class ProfileTaskSubmitRequest {
    "profileId": string;
    "name"?: string;
    "preset": string;
    "config"?: interfaces$0.TaskConfig;

    /** Creates a new ProfileTaskSubmitRequest instance. */
    constructor($$source: Partial<ProfileTaskSubmitRequest> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileTaskSubmitRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileTaskSubmitRequest {
        const $$createField3_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField3_0($$parsedSource["config"]);
        }
        return new ProfileTaskSubmitRequest($$parsedSource as Partial<ProfileTaskSubmitRequest>);
    }
}

// Private type creation functions
const $$createType0 = interfaces$0.RuntimeStatus.createFrom;
const $$createType1 = interfaces$0.TaskConfig.createFrom;
