// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as interfaces$0 from "../sakiko.local/sakiko-core/interfaces/models.js";

export class AppSettings {
    "language": string;
    "dns": interfaces$0.DNSConfig;

    /** Creates a new AppSettings instance. */
    constructor($$source: Partial<AppSettings> = {}) {
        if (!("language" in $$source)) {
            this["language"] = "";
        }
        if (!("dns" in $$source)) {
            this["dns"] = (new interfaces$0.DNSConfig());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettings instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettings {
        const $$createField1_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        return new AppSettings($$parsedSource as Partial<AppSettings>);
    }
}

export class AppSettingsPatch {
    "language"?: string;
    "dns"?: interfaces$0.DNSConfig | null;

    /** Creates a new AppSettingsPatch instance. */
    constructor($$source: Partial<AppSettingsPatch> = {}) {

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppSettingsPatch instance from a string or object.
     */
    static createFrom($$source: any = {}): AppSettingsPatch {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("dns" in $$parsedSource) {
            $$parsedSource["dns"] = $$createField1_0($$parsedSource["dns"]);
        }
        return new AppSettingsPatch($$parsedSource as Partial<AppSettingsPatch>);
    }
}

export class DesktopStatus {
    "profilesPath": string;
    "runtime": interfaces$0.RuntimeStatus;
    "mihomoVersion"?: string;
    "networkEnv": interfaces$0.BackendInfo;

    /** Creates a new DesktopStatus instance. */
    constructor($$source: Partial<DesktopStatus> = {}) {
        if (!("profilesPath" in $$source)) {
            this["profilesPath"] = "";
        }
        if (!("runtime" in $$source)) {
            this["runtime"] = (new interfaces$0.RuntimeStatus());
        }
        if (!("networkEnv" in $$source)) {
            this["networkEnv"] = (new interfaces$0.BackendInfo());
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DesktopStatus instance from a string or object.
     */
    static createFrom($$source: any = {}): DesktopStatus {
        const $$createField1_0 = $$createType2;
        const $$createField3_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("runtime" in $$parsedSource) {
            $$parsedSource["runtime"] = $$createField1_0($$parsedSource["runtime"]);
        }
        if ("networkEnv" in $$parsedSource) {
            $$parsedSource["networkEnv"] = $$createField3_0($$parsedSource["networkEnv"]);
        }
        return new DesktopStatus($$parsedSource as Partial<DesktopStatus>);
    }
}

export class ProfileSummary {
    "id": string;
    "name": string;
    "source": string;
    "updatedAt"?: string;
    "nodeCount": number;
    "remainingBytes"?: number;
    "expiresAt"?: string;

    /** Creates a new ProfileSummary instance. */
    constructor($$source: Partial<ProfileSummary> = {}) {
        if (!("id" in $$source)) {
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            this["name"] = "";
        }
        if (!("source" in $$source)) {
            this["source"] = "";
        }
        if (!("nodeCount" in $$source)) {
            this["nodeCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileSummary instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileSummary {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileSummary($$parsedSource as Partial<ProfileSummary>);
    }
}

export class ProfileTaskSubmitRequest {
    "profileId": string;
    "name"?: string;
    "preset": string;
    "presets"?: string[];
    "config"?: interfaces$0.TaskConfig;

    /** Creates a new ProfileTaskSubmitRequest instance. */
    constructor($$source: Partial<ProfileTaskSubmitRequest> = {}) {
        if (!("profileId" in $$source)) {
            this["profileId"] = "";
        }
        if (!("preset" in $$source)) {
            this["preset"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileTaskSubmitRequest instance from a string or object.
     */
    static createFrom($$source: any = {}): ProfileTaskSubmitRequest {
        const $$createField3_0 = $$createType4;
        const $$createField4_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("presets" in $$parsedSource) {
            $$parsedSource["presets"] = $$createField3_0($$parsedSource["presets"]);
        }
        if ("config" in $$parsedSource) {
            $$parsedSource["config"] = $$createField4_0($$parsedSource["config"]);
        }
        return new ProfileTaskSubmitRequest($$parsedSource as Partial<ProfileTaskSubmitRequest>);
    }
}

export class ReleaseCheckResult {
    "currentVersion": string;
    "latestVersion"?: string;
    "releaseName"?: string;
    "releaseURL"?: string;
    "hasUpdate": boolean;
    "checkedAt"?: string;

    /** Creates a new ReleaseCheckResult instance. */
    constructor($$source: Partial<ReleaseCheckResult> = {}) {
        if (!("currentVersion" in $$source)) {
            this["currentVersion"] = "";
        }
        if (!("hasUpdate" in $$source)) {
            this["hasUpdate"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ReleaseCheckResult instance from a string or object.
     */
    static createFrom($$source: any = {}): ReleaseCheckResult {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ReleaseCheckResult($$parsedSource as Partial<ReleaseCheckResult>);
    }
}

// Private type creation functions
const $$createType0 = interfaces$0.DNSConfig.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = interfaces$0.RuntimeStatus.createFrom;
const $$createType3 = interfaces$0.BackendInfo.createFrom;
const $$createType4 = $Create.Array($Create.Any);
const $$createType5 = interfaces$0.TaskConfig.createFrom;
