// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as interfaces$0 from "../sakiko.local/sakiko-core/interfaces/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function CancelTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(886078340, taskID);
}

export function CheckForUpdates(): $CancellablePromise<$models.ReleaseCheckResult> {
    return $Call.ByID(3870971566).then(($result: any) => {
        return $$createType0($result);
    });
}

export function DeleteProfile(profileID: string): $CancellablePromise<void> {
    return $Call.ByID(1089376541, profileID);
}

export function DeleteResultArchive(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(2777901225, taskID);
}

export function DeleteTask(taskID: string): $CancellablePromise<void> {
    return $Call.ByID(3324671101, taskID);
}

export function DesktopStatus(): $CancellablePromise<$models.DesktopStatus> {
    return $Call.ByID(3020181611).then(($result: any) => {
        return $$createType1($result);
    });
}

export function GetAppSettings(): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(3806880337).then(($result: any) => {
        return $$createType2($result);
    });
}

export function GetProfile(profileID: string): $CancellablePromise<interfaces$0.Profile> {
    return $Call.ByID(2905535086, profileID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function GetResultArchive(taskID: string): $CancellablePromise<interfaces$0.ResultArchive> {
    return $Call.ByID(962886202, taskID).then(($result: any) => {
        return $$createType4($result);
    });
}

export function GetTask(taskID: string): $CancellablePromise<interfaces$0.TaskStatusResponse> {
    return $Call.ByID(3172388588, taskID).then(($result: any) => {
        return $$createType5($result);
    });
}

export function ImportProfile(req: interfaces$0.ProfileImportRequest): $CancellablePromise<interfaces$0.Profile> {
    return $Call.ByID(3970473967, req).then(($result: any) => {
        return $$createType3($result);
    });
}

export function ListDownloadTargets(): $CancellablePromise<interfaces$0.DownloadTarget[]> {
    return $Call.ByID(494326779).then(($result: any) => {
        return $$createType7($result);
    });
}

export function ListProfileSummaries(): $CancellablePromise<$models.ProfileSummary[]> {
    return $Call.ByID(1419878352).then(($result: any) => {
        return $$createType9($result);
    });
}

export function ListProfiles(): $CancellablePromise<interfaces$0.Profile[]> {
    return $Call.ByID(3019865565).then(($result: any) => {
        return $$createType10($result);
    });
}

export function ListResultArchives(): $CancellablePromise<interfaces$0.ResultArchiveListItem[]> {
    return $Call.ByID(1131350281).then(($result: any) => {
        return $$createType12($result);
    });
}

export function ListTasks(): $CancellablePromise<interfaces$0.TaskState[]> {
    return $Call.ByID(3175697171).then(($result: any) => {
        return $$createType14($result);
    });
}

export function MoveProfileNode(profileID: string, nodeIndex: number, targetIndex: number): $CancellablePromise<interfaces$0.Profile> {
    return $Call.ByID(1514293423, profileID, nodeIndex, targetIndex).then(($result: any) => {
        return $$createType3($result);
    });
}

export function OpenReleasePage(url: string): $CancellablePromise<void> {
    return $Call.ByID(2795718631, url);
}

export function RefreshProfile(profileID: string): $CancellablePromise<interfaces$0.Profile> {
    return $Call.ByID(4151267443, profileID).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SearchDownloadTargets(search: string): $CancellablePromise<interfaces$0.DownloadTarget[]> {
    return $Call.ByID(1965905147, search).then(($result: any) => {
        return $$createType7($result);
    });
}

export function SetProfileNodeEnabled(profileID: string, nodeIndex: number, enabled: boolean): $CancellablePromise<interfaces$0.Profile> {
    return $Call.ByID(3960989747, profileID, nodeIndex, enabled).then(($result: any) => {
        return $$createType3($result);
    });
}

export function SubmitProfileTask(req: $models.ProfileTaskSubmitRequest): $CancellablePromise<string> {
    return $Call.ByID(737454241, req);
}

export function UpdateAppSettings(patch: $models.AppSettingsPatch): $CancellablePromise<$models.AppSettings> {
    return $Call.ByID(764100292, patch).then(($result: any) => {
        return $$createType2($result);
    });
}

// Private type creation functions
const $$createType0 = $models.ReleaseCheckResult.createFrom;
const $$createType1 = $models.DesktopStatus.createFrom;
const $$createType2 = $models.AppSettings.createFrom;
const $$createType3 = interfaces$0.Profile.createFrom;
const $$createType4 = interfaces$0.ResultArchive.createFrom;
const $$createType5 = interfaces$0.TaskStatusResponse.createFrom;
const $$createType6 = interfaces$0.DownloadTarget.createFrom;
const $$createType7 = $Create.Array($$createType6);
const $$createType8 = $models.ProfileSummary.createFrom;
const $$createType9 = $Create.Array($$createType8);
const $$createType10 = $Create.Array($$createType3);
const $$createType11 = interfaces$0.ResultArchiveListItem.createFrom;
const $$createType12 = $Create.Array($$createType11);
const $$createType13 = interfaces$0.TaskState.createFrom;
const $$createType14 = $Create.Array($$createType13);
