import { readFileSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const repoRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");

function normalizeVersion(source) {
  const raw = String(source || "").trim();
  const version = raw.replace(/^v/i, "");
  if (!/^\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/.test(version)) {
    throw new Error(`Invalid Sakiko version: ${raw || "<empty>"}`);
  }
  return version;
}

function readVersionFromSource() {
  const explicit = process.argv[2] || process.env.SAKIKO_VERSION;
  if (explicit) {
    return normalizeVersion(explicit);
  }

  const githubRefName = process.env.GITHUB_REF_NAME || "";
  if (/^v\d+\.\d+\.\d+(?:[-+][0-9A-Za-z.-]+)?$/i.test(githubRefName)) {
    return normalizeVersion(githubRefName);
  }

  return normalizeVersion(readFileSync(resolve(repoRoot, "VERSION"), "utf8"));
}

function writeText(relativePath, value) {
  writeFileSync(resolve(repoRoot, relativePath), value, "utf8");
}

function readText(relativePath) {
  return readFileSync(resolve(repoRoot, relativePath), "utf8");
}

function updateText(relativePath, updater) {
  const current = readText(relativePath);
  const next = updater(current);
  if (next !== current) {
    writeText(relativePath, next);
  }
}

function replaceRequired(text, pattern, replacement, label) {
  if (!pattern.test(text)) {
    throw new Error(`Unable to update ${label}`);
  }
  return text.replace(pattern, replacement);
}

function updateJson(relativePath, updater) {
  const path = resolve(repoRoot, relativePath);
  const data = JSON.parse(readFileSync(path, "utf8"));
  updater(data);
  writeFileSync(path, `${JSON.stringify(data, null, 2)}\n`, "utf8");
}

function updatePlistVersion(relativePath, version, options = {}) {
  const shortVersion = options.shortVersion || version;
  updateText(relativePath, (text) => {
    let next = replaceRequired(
      text,
      /(<key>CFBundleShortVersionString<\/key>\s*<string>)[^<]+(<\/string>)/,
      `$1${shortVersion}$2`,
      `${relativePath} CFBundleShortVersionString`,
    );
    next = replaceRequired(
      next,
      /(<key>CFBundleVersion<\/key>\s*<string>)[^<]+(<\/string>)/,
      `$1${version}$2`,
      `${relativePath} CFBundleVersion`,
    );
    return next;
  });
}

const version = readVersionFromSource();
const numericVersion = version.match(/^\d+\.\d+\.\d+/)[0];
const windowsPackageVersion = `${numericVersion}.0`;

writeText("VERSION", `${version}\n`);

writeText(
  "sakiko-core/app/version_generated.go",
  `// Code generated by scripts/sync-version.mjs; DO NOT EDIT.\n\npackage app\n\nconst DefaultAppVersion = "${version}"\n`,
);

writeText(
  "sakiko-wails/frontend/src/constants/version.generated.ts",
  `// Code generated by scripts/sync-version.mjs; DO NOT EDIT.\n\nexport const APP_VERSION_VALUE = "${version}";\n`,
);

updateJson("sakiko-wails/frontend/package.json", (data) => {
  data.version = version;
});

updateText("sakiko-wails/build/windows/info.json", (text) => {
  let next = replaceRequired(text, /("file_version":\s*")[^"]+(")/, `$1${numericVersion}$2`, "Windows file_version");
  next = replaceRequired(next, /("ProductVersion":\s*")[^"]+(")/, `$1${version}$2`, "Windows ProductVersion");
  return next;
});

updateText("sakiko-wails/build/config.yml", (text) =>
  replaceRequired(
    text,
    /(info:\s*(?:\r?\n  [^\r\n]*)*\r?\n  version:\s*")[^"]+(")/,
    `$1${version}$2`,
    "build/config.yml info.version",
  ),
);

updateText("sakiko-wails/build/windows/wails.exe.manifest", (text) =>
  replaceRequired(
    text,
    /(<assemblyIdentity type="win32" name="io\.github\.kanda-akihito-kun\.sakiko" version=")[^"]+(")/,
    `$1${numericVersion}$2`,
    "windows manifest version",
  ),
);

updateText("sakiko-wails/build/windows/nsis/wails_tools.nsh", (text) =>
  replaceRequired(
    text,
    /(!define INFO_PRODUCTVERSION ")[^"]+(")/,
    `$1${version}$2`,
    "NSIS product version",
  ),
);

updateText("sakiko-wails/build/windows/msix/template.xml", (text) =>
  replaceRequired(text, /(Version=")[^"]+(")/, `$1${windowsPackageVersion}$2`, "MSIX template version"),
);

updateText("sakiko-wails/build/windows/msix/app_manifest.xml", (text) =>
  replaceRequired(text, /(Version=")[^"]+(")/, `$1${windowsPackageVersion}$2`, "MSIX manifest version"),
);

updatePlistVersion("sakiko-wails/build/darwin/Info.plist", version);
updatePlistVersion("sakiko-wails/build/darwin/Info.dev.plist", version);
updatePlistVersion("sakiko-wails/build/ios/Info.plist", version);
updatePlistVersion("sakiko-wails/build/ios/Info.dev.plist", version, { shortVersion: `${version}-dev` });

updateText("sakiko-wails/build/linux/nfpm/nfpm.yaml", (text) =>
  replaceRequired(text, /^(version:\s*")[^"]+(")$/m, `$1${version}$2`, "nfpm version"),
);

updateText("sakiko-wails/build/ios/build.sh", (text) => {
  let next = replaceRequired(text, /^(VERSION=")[^"]+(")$/m, `$1${version}$2`, "iOS VERSION");
  next = replaceRequired(next, /^(BUILD_NUMBER=")[^"]+(")$/m, `$1${numericVersion}$2`, "iOS BUILD_NUMBER");
  return next;
});

console.log(`Sakiko version synchronized: ${version}`);
